apiVersion: v2
version: 0.1.0
name: prometheus-postgresql-exporter
description: Collects postgres metrics and writes them to prometheus
dependencies:
  - name: prometheus-postgres-exporter
    repository: https://prometheus-community.github.io/helm-charts
    version: 4.7.0